### ISSUE TITLE
fix "Open in Apollo" extension in Safari

### ISSUE THREAD

**Issue by static-pixel** [JeffreyCA/Apollo-ImprovedCustomApi#14]
Top app banner is required to hit on "Open" for the extension to automatically open the Apollo app. However, the banner suggests downloading the app from the AppStore instead of using the sideloaded version. The extension is open sourced here already. 

https://github.com/christianselig/OpenInApolloExtension

![9ZTyoIN](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/assets/13009943/8acebd76-351f-44fe-a198-1e251b6c41b7)

**Comment by JackPlaysGames0510** [comment]
I think it’s a sideload  problem because it’s like with YouTube and Spotify

**Comment by samuelawachie** [comment]
To solve this problem quite a bit,
# download Hyperweb
# in Hyperweb, tap "Open Links in Apps"
# enable the switch for Apollo
# enable Hyperweb in Settings from the Safari Extensions page 
# reload Safari browser
Now when you open a hyperlink that redirects to reddit (usually from google search results), it should just give one "Open in Apollo" popup. 
This does not work automatically, even if you set it to do so automatically. I think that functionality had to be degraded after the official Apollo API shutdown but it certainly is faster, and doesn't load the reddit page in the browser as well as opening it in Apollo (thereby, saving on data costs and enhancing performance)

**Comment by JackPlaysGames0510** [comment]
Still the same thing
