### ISSUE TITLE
Cannot add account

### ISSUE THREAD

**Issue by karanf** [JeffreyCA/Apollo-ImprovedCustomApi#16]
When I try to add an account, it opens the reddit login, after which Reddit asks to give permissions for the app to access my account. When I 'Agree', I get redirected to a page which only shows {}. The account does not get added.

**Comment by jiznon** [comment]
Same issue here.

**Comment by ArmandAgopian** [comment]
One workaround is "Request Desktop Website" under "aA" menu before entering the credentials.

**Comment by JeffreyCA** [comment]
Thanks for the workaround, it seems to be a temporary issue that's fixed now
