### ISSUE TITLE
Imgur upload failing

### ISSUE THREAD

**Issue by tangchr1** [JeffreyCA/Apollo-ImprovedCustomApi#20]
For the past few week uploading to Imgur has been failing with an error message. ![image](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/assets/155857991/e380a15e-7866-49e4-a298-46fed9d580f4)

**Comment by JeffreyCA** [comment]
Thanks for the report, looks like something may have changed in the Imgur API. This should be fixed in [v1.0.11](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/releases/tag/v1.0.11).

**Comment by JeffreyCA** [comment]
Thanks for confirming! Closing as resolved

**Comment by tangchr1** [comment]
Thanks again!!
