### ISSUE TITLE
I keep getting this error when using Sideloadly

### ISSUE THREAD

**Issue by Apevio** [JeffreyCA/Apollo-ImprovedCustomApi#21]
I downloaded the latest release and renamed the ApolloImprovedCustomApi.plist to ApolloImprovedCustomApi.ipa, 
Then I did the inject dylib/framework thing, but I keep getting this error "Install failed: Guru Meditation b4822c@1336:28f336 File is not a zip file”

**Comment by JeffreyCA** [comment]
Hi, you shouldn't need to rename any files. You need an unmodded .ipa of Apollo - version 1.15.11 is recommended.
