### ISSUE TITLE
Error Loading Posts

### ISSUE THREAD

**Issue by pfych** [JeffreyCA/Apollo-ImprovedCustomApi#23]
The app has been working great for me for a few months but this morning when attempting to access any page in-app I get errors like “Error fetching overview” & “Error fetching posts”

I’ve attempted signing in with different accounts as well as recreating my reddit API key yet the issue still persists.

How would I go about debugging this issue & providing more details?

**Comment by drsoupyy** [comment]
Same issue here - Take a look here https://www.reddit.com/r/redditdev/comments/1calkb3/reddit_api_throwing_500_errora/ & Reddit Status (https://www.redditstatus.com/) showing degraded service currently. 

Looks like they have something going on with their API.

**Comment by pfych** [comment]
Yeah it looks like Reddit’s API had some hiccups and it just so happened to line up with my troubleshooting!
