### ISSUE TITLE
Reddit is blocking the original Bundle Identifier

### ISSUE THREAD

**Issue by Cyphs** [JeffreyCA/Apollo-ImprovedCustomApi#29]
Today, sideloaded Apollo stopped working for users. However some users pointed out that the IPA from [Balackburn](https://github.com/Balackburn/Apollo) still works.

However I’ve just seemed to confirm that the IPA doesn’t matter, it’s the Bundle Identifier. If it is using the original BundleId, `com.christianselig.Apollo`, it will not work, but anything else seems to work for now. Balackburn’s IPA is using `com.foo.Apollo` for its Bundle Identifier which is why it’s working.

—-
Also a warning to Reddit users sideloading Apollo: I received an e-mail from Reddit after logging in a third time that says:
“At Reddit, we’re always watching out for your privacy, safety, and security. Recently, after detecting some technical irregularities on your u/_ account, we took the extra precaution of locking your account. To unlock your account, reset your password now.”

So your account can become temporarily suspended doing this. Maybe even banned in the near future, hopefully not.

**Comment by neldonado** [comment]
I also stopped being able to use the app.

**Comment by reticivis-net** [comment]
Can confirm the issue is the bundle ID, I installed ICAPI with the com.foo.Apollo bundle ID and it works fine.

**Comment by samuelawachie** [comment]
What do you reckon is the significance of the bundle identifier on a tweak like this? Does this mean that if this working one is blocked, we can't put in another one?

**Comment by reticivis-net** [comment]
We can put another bundle ID for now, but hopefully the tweak will spoof a random one to Reddit

**Comment by ViRb3** [comment]
The reason this is happening is because Apollo uses the bundle identifier in its user agent. By changing the bundle identifier, you are in turn changing the user agent, which happens to bypass Reddit's blocklist. I wonder how long before they switch to an allowlist...

**Comment by reticivis-net** [comment]
Then all that needs to be done is to spoof the user agent to something random or based on the custom api or official

**Comment by thexYeti** [comment]
Bundle ID might be correlated but it isn’t the sole culprit. I was using ImprovedCustomAPI on Apollo 1.15.11 with a modified bundle id and it stopped working today, while my other install with Artemis on Apollo 1.14.26 and original bundle id is still working fine.

**Comment by paradoxally** [comment]
I have created a [simple tweak](https://github.com/paradoxally/Apollo-User-Agent-Fix) that solves this issue by replacing Apollo's user agent with one from a common browser. 

There is no need to change bundle ID with this, it simply overwrites the User Agent header if the request is for the reddit API.

Ideally, this code can be copied and pasted into a larger tweak that has more features such as this one.

Enjoy.

**Comment by JeffreyCA** [comment]
> The reason this is happening is because Apollo uses the bundle identifier in its user agent. By changing the bundle identifier, you are in turn changing the user agent, which happens to bypass Reddit's blocklist. I wonder how long before they switch to an allowlist...

Yep this seems to be what's happening, just pushed an update to use a generic user agent: [v1.0.12](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/releases/tag/v1.0.12). Thanks all for the report and findings

**Comment by samuelawachie** [comment]
Amazing we have such smart people here, but we still have the new comment highlightifier issue ongoing. C'mon guys

**Comment by dhdeanha** [comment]
Hi,

it seems like Apollo is broken and am curious if changing the useragent will make it working again. Perhaps a button to set a custom useragent manually or generate/randomize one?
