### ISSUE TITLE
Disable the announcement banner

### ISSUE THREAD

**Issue by mustafacakirogludev** [JeffreyCA/Apollo-ImprovedCustomApi#3]
Hey, first of all, amazing work!

I was hoping you can somehow remove/block the banner that advertises apollo merch once in a while when we open the app. According to the changelog of version 1.0.1 you already done it but I started seeing a different one recently. If it helps, I believe it pulls the data from apollogur.download url. I'd really appreciate you keeping this issue in mind in your future releases.

![IMG_1363](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/assets/101709759/2693c083-deea-4208-8df8-556e6674fe8a)

**Comment by mustafacakirogludev** [comment]
Thanks for the quick fix!

**Comment by JeffreyCA** [comment]
Sorry forgot to reply, thanks for reporting this issue! I just released a new update with share link support if you're interested.

**Comment by Fofer** [comment]
> Would it be possible to make this feature a toggle? 

@Proaxel, I haven't been able to locate it yet, but this forked .ipa says it includes "toggleable settings for blocking announcements"

https://github.com/Balackburn/Apollo/releases/tag/v1.15.11-1.0.7
