### ISSUE TITLE
I’m having trouble logging in

### ISSUE THREAD

**Issue by JackPlaysGames0510** [JeffreyCA/Apollo-ImprovedCustomApi#30]

**Comment by JackPlaysGames0510** [comment]
It just loads forever

**Comment by faker-ino** [comment]
Same problem here, suddenly no account and no feed will be loaded. API key still there, nothing changed on my side.
App just endless loading

**Comment by JackPlaysGames0510** [comment]
Just completely change the bundle id

**Comment by ConnorDoesDev** [comment]
any fix?

**Comment by JackPlaysGames0510** [comment]
my last comment is the fix

**Comment by JeffreyCA** [comment]
I think Reddit or their API might've been temporarily down during that particular time, feel free to reopen if this still persists.
