### ISSUE TITLE
Imgur issues again?

### ISSUE THREAD

**Issue by kisenakamoto** [JeffreyCA/Apollo-ImprovedCustomApi#35]
Is it just on my device or Imgur has stopped working again? Just the same **Imgur error Tap to open in browser.**

**Comment by JeffreyCA** [comment]
Yeah it looks like something in their API changed for newer images and albums. Thanks for reporting, will take a look soon

**Comment by JeffreyCA** [comment]
This is fixed in [v1.1.3](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/releases/tag/v1.1.3)! Let me know if you still see issues with certain URLs

**Comment by kisenakamoto** [comment]
Thanks boss!! Will try it later
