### ISSUE TITLE
Find installed version

### ISSUE THREAD

**Issue by Leonito2003** [JeffreyCA/Apollo-ImprovedCustomApi#37]
Is there a way to check the currently installed version ? I´m pretty sure SideStore never updates the app even though I added the source, but I can't find a way to check. I looked in the UI and even in the bundle using the debugger but I couldn't find anything.

**Comment by JeffreyCA** [comment]
Thanks for the feedback, I've included this in [v1.1.5](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/releases/tag/v1.1.5) going forward.

**Comment by samuelawachie** [comment]
> Thanks for the feedback, I've included this in [v1.1.5](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/releases/tag/v1.1.5) going forward.
>
So where can we find it?

**Comment by samuelawachie** [comment]
Just installed the 1.1.5b, and I _still_ can't see the tweak version in the Custom API settings page.

**Comment by JeffreyCA** [comment]
> Just installed the 1.1.5b, and I _still_ can't see the tweak version in the Custom API settings page.

It should be at the very bottom, is it not appearing for you?

![IMG_3469](https://github.com/user-attachments/assets/3ab19a3d-4c37-47a2-b0eb-9a9580e5bb87)

**Comment by samuelawachie** [comment]
>
> It should be at the very bottom, is it not appearing for you?
> 
No. That place is just blank.

**Comment by samuelawachie** [comment]
@CySxL Does it show for you in the CustomAPI settings?

**Comment by samuelawachie** [comment]
> 
> It should be at the very bottom, is it not appearing for you?
> 
It only shows if the bundleID is the now blocked com.CristianSelig.Apollo. If you change it to the preferred com.foo.Apollo, it doesn't show

**Comment by CySxL** [comment]
> @CySxL Does it show for you in the CustomAPI settings?

Haven't tried it since I don't have time to convert it to rootless tho.

Using Dopamine rn.
