### ISSUE TITLE
Issue Getting API Key

### ISSUE THREAD

**Issue by xM4ddy** [JeffreyCA/Apollo-ImprovedCustomApi#38]
Following Guide To Get API Key and Ran Into This Issue on https://www.reddit.com/prefs/apps when creating the app

![image](https://github.com/user-attachments/assets/b5ab507b-375e-43fe-b1a6-6de5aa3cbc1d)

**Comment by JeffreyCA** [comment]
Can you doublecheck if you selected "installed app" and not "web app"?

**Comment by xM4ddy** [comment]
> Can you doublecheck if you selected "installed app" and not "web app"?

Wow I shouldn’t do this stuff before coffee🙃 thanks :)
