### ISSUE TITLE
Handle np links in app

### ISSUE THREAD

**Issue by StudentBlake** [JeffreyCA/Apollo-ImprovedCustomApi#42]
No Participation links currently open in browser. If possible, can redirection be handled in app?

https://www.reddit.com/r/NoParticipation/wiki/intro/

**Comment by StudentBlake** [comment]
Apologies for closing and reopening. It seems like np links are handled but this new format link isn’t:

https://np.reddit.com/r/lego/s/MSMAMeXdW5

**Comment by JeffreyCA** [comment]
Thanks for reporting this! This is now fixed in [v1.1.7](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/releases/tag/v1.1.7)
