### ISSUE TITLE
Problem With Redgifs API or Maybe URL

### ISSUE THREAD

**Issue by zoooobie** [JeffreyCA/Apollo-ImprovedCustomApi#48]
On the Sideloaded Apollo App we are able to hear the Audio of the Videos of REDGIFs which are played but recently we are unable to do so because, On the URL of the video there is 

(⚠️NSFW⚠️)

Current URL: https://files.redgifs.com/LooseRoyalPlainsqueaker-silent.mp4 (-silent) tag. 

 Old URL: https://files.redgifs.com/LooseRoyalPlainsqueaker.mp4 (which didn’t had that -silent tag worked perfectly) 

This Sound Icon is showing and even sync with video’s sounds but no audio is in the URL the sound is not coming please fix up this issue in your URL.

This might be a Apollo Problem too, Please look up on the matter

**Comment by iCrazeiOS** [comment]
https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/pull/49
