### ISSUE TITLE
[Feature Request] [Reddit API Update] Random API removed

### ISSUE THREAD

**Issue by yodaluca23** [JeffreyCA/Apollo-ImprovedCustomApi#50]
Reddit recently decided to lovingly remove the Random Subreddit API. https://reddit.com/r/help/comments/1fojw02/cleaning_up_some_lowusage_features

It would be awesome, if this tweak could make its own random subreddit fetcher, not dependent on Reddits API, and use that for the Apollo random button.

**Comment by iCrazeiOS** [comment]
Could maybe pick a random subreddit from the plist used here: https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/pull/12/commits/49a7c673383d890438d8d30ab5ffb099acfb85b0

**Comment by yodaluca23** [comment]
Works great thanks!
One thing though for the trending Subreddits limits, maybe instead of have a switch of limiting to 5 trending subs or not, have a field that by default is set to "5", but let the user change it to limit it to however many they want, then say something like "Set to 0 for no limit."

**Comment by yodaluca23** [comment]
https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/commit/2125eac6c5debd50c15463971f126a21ce40f42f Thank You!

**Comment by JeffreyCA** [comment]
Good point, re-released 1.2.1 with that customization option
