### ISSUE TITLE
SideStore/AltStore repo?

### ISSUE THREAD

**Issue by abjugard** [JeffreyCA/Apollo-ImprovedCustomApi#6]
This tweak looks amazing! Thank you for making it! Do you happen to know if anyone has already baked this into a 1.5.11 IPA and set it up on a SideStore/AltStore repo?

**Comment by abjugard** [comment]
Wow, that's fast work haha.

**Comment by Write** [comment]
> I guess @Balackburn is probably on vacation or something, but their repo hasn't been updated with 1.1.1 as of yet.
> 
> @JeffreyCA do you have an original unmodified Apollo 1.15.11 IPA? If so I'd be keen to setup my own little repo. Looked around for it, but can't find it for the life of me.

He has updated it.
